@echo off
@echo Project assembly, please wait...
@del /Q linux_app > NUL 2>&1
@wsl `wx-config --cxx --cxxflags` `pkg-config --cflags gtk+-3.0` -o linux_app *.cpp `wx-config --libs` `pkg-config --libs gtk+-3.0` -lsqlite3
@echo Program launch, please wait...
@wsl ./linux_app
